name: Scheduled Analysis

on:
  schedule:
    - cron: '0 * * * *' # 1時間に1回実行
  workflow_dispatch:      # 手動実行ボタンも作成

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run crawler
        run: python analysis/crawler.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/data/latest_runs.json
          git commit -m "Update latest runs data" || exit 0
          git push